import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/src/i18n/routing';

import RainbowKitAndWagmiProvider from "../RainbowKitAndWagmiProvider";
import Layout from "@/src/components/shared/PageLayout/Layout";
import { Toaster } from "@/src/components/ui/sonner"
import { getTranslations, setRequestLocale } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export async function generateMetadata(props: Omit<LayoutProps<'/[locale]'>, 'children'>) {
  return {
    title: 'PLAY - DARE - WIN'
  };
}

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export default async function RootLayout({children, params}: Props) {

  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RainbowKitAndWagmiProvider>
          {/* <Layout> */}
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          {/* </Layout> */}
        </RainbowKitAndWagmiProvider>
        <Toaster richColors/>
      </body>
    </html>
  );
}
