name: Test Unitaires

on:
  push:
    branches: [main]
    paths:
      - 'backend/**' # trigger only when backend files change

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npx hardhat test
